language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install -r requirements.txt
jobs:
  include:
    - stage: unit_testing
    script:
      - python algo.py
    
    - stage: integ_testing
    script:
      - python integ.py
    
    - stage: stress_testing
    script:
      - python stress.py